import { ArrowUp, ArrowDown, Filter, ArrowLeftRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useWallet, useTransactions } from '@/hooks/use-wallet';
import { useAccountTransactions } from '@/hooks/use-xrpl';
import { xrplClient } from '@/lib/xrpl-client';
import { extractOfferFills, calculateBalanceChanges, enrichOfferWithStatus } from '@/lib/dex-utils';
import { browserStorage } from '@/lib/browser-storage';

import { useEffect } from 'react';

export default function Transactions() {
  const { currentWallet } = useWallet();
  const network = currentWallet?.network ?? 'mainnet';
  const { data: dbTransactions, isLoading: dbLoading } = useTransactions(currentWallet?.id || null);
  const { data: xrplTransactions, isLoading: xrplLoading } = useAccountTransactions(currentWallet?.address || null, network);

  const isLoading = dbLoading || xrplLoading;
  const currentNetwork = network;
  
  // Process and save offer fills from transaction metadata (run once when transactions change)
  useEffect(() => {
    if (!xrplTransactions?.transactions || !currentWallet) return;
    
    // FIRST PASS: Save all OfferCreate transactions with authoritative original amounts
    // This must happen BEFORE processing fills to avoid creating placeholders with wrong amounts
    xrplTransactions.transactions.forEach((tx: any) => {
      const transaction = tx.tx_json || tx.tx || tx;
      const txHash = transaction.hash || tx.hash;
      
      if (transaction.TransactionType === 'OfferCreate' && transaction.Account === currentWallet.address) {
        const existingOffer = browserStorage.getOffer(currentWallet.address, network, transaction.Sequence);
        
        // Create or update the stored offer with TRUE original amounts from the transaction
        const storedOffer = {
          sequence: transaction.Sequence,
          walletAddress: currentWallet.address,
          network: network,
          originalTakerGets: transaction.TakerGets,
          originalTakerPays: transaction.TakerPays,
          createdAt: transaction.date ? (transaction.date * 1000 + 946684800000) : Date.now(),
          createdTxHash: txHash,
          createdLedgerIndex: tx.ledger_index || tx.ledger_current_index || 0,
          fills: existingOffer?.fills || [], // Preserve existing fills if any
          expiration: transaction.Expiration,
          flags: transaction.Flags
        };
        
        browserStorage.saveOffer(storedOffer);
      }
    });
    
    // SECOND PASS: Process fills now that all offers have correct original amounts
    xrplTransactions.transactions.forEach((tx: any) => {
      const offerFills = extractOfferFills(tx, currentWallet.address);
      if (offerFills.length > 0) {
        offerFills.forEach(fill => {
          console.log('Processing DEX fill for offer sequence:', fill.offerSequence, fill.txHash);
          browserStorage.addOfferFill(currentWallet.address, network, fill.offerSequence, {
            txHash: fill.txHash,
            timestamp: fill.timestamp,
            ledgerIndex: fill.ledgerIndex,
            takerGotAmount: fill.takerGotAmount,
            takerPaidAmount: fill.takerPaidAmount,
            executionPrice: fill.executionPrice
          });
        });
      }
    });
  }, [xrplTransactions, currentWallet, network]);
  
  const getXRPScanUrl = (hash: string) => {
    const baseUrl = currentNetwork === 'mainnet' 
      ? 'https://xrpscan.com' 
      : 'https://testnet.xrpscan.com';
    return `${baseUrl}/tx/${hash}`;
  };

  // Combine and format transactions from both sources
  const formatTransactions = () => {
    const transactions: any[] = [];

    // Preload stored offers for enrichment
    const storedOffers = currentWallet 
      ? browserStorage.getOffersByWallet(currentWallet.address, network)
      : [];
    
    // Create maps for quick lookup by both transaction hash AND sequence number
    // (sequence number is more reliable for historical fills that don't have createdTxHash)
    const offersByTxHash = new Map(
      storedOffers
        .filter(offer => offer.createdTxHash) // Only map non-empty tx hashes
        .map(offer => [offer.createdTxHash, offer])
    );
    
    const offersBySequence = new Map(
      storedOffers.map(offer => [offer.sequence, offer])
    );

    // Add XRPL transactions first
    if (xrplTransactions?.transactions) {
      xrplTransactions.transactions.forEach((tx: any) => {
        // Handle both tx.tx_json (historical) and tx structure (real-time)
        const transaction = tx.tx_json || tx.tx || tx;
        
        if (transaction?.TransactionType === 'Payment') {
          // Check if this payment was generated by an offer fill (fills are saved in useEffect)
          const offerFills = currentWallet ? extractOfferFills(tx, currentWallet.address) : [];
          const isDEXFill = offerFills.length > 0;
          
          // Calculate actual balance changes from metadata (more accurate for DEX fills)
          const balanceChanges = currentWallet ? calculateBalanceChanges(tx, currentWallet.address) : { xrpChange: null, tokenChanges: [] };
          
          
          // Skip transactions where current wallet is neither sender nor receiver
          // UNLESS there are balance changes (which means we're involved indirectly via DEX)
          const isSender = transaction.Account === currentWallet?.address;
          const isReceiver = transaction.Destination === currentWallet?.address;
          const hasBalanceChanges = balanceChanges.xrpChange || balanceChanges.tokenChanges.length > 0;
          
          if (!isSender && !isReceiver && !hasBalanceChanges) {
            return; // Skip this transaction
          }
          
          let displayAmount = '';
          let isOutgoing = isSender;
          
          // For DEX fills, show both sides of the trade (what was paid and what was received)
          if (isDEXFill || hasBalanceChanges) {
            const increases: string[] = [];
            const decreases: string[] = [];
            
            // Add XRP changes
            if (balanceChanges.xrpChange) {
              const xrpDisplay = `${balanceChanges.xrpChange.replace('-', '')} XRP`;
              if (balanceChanges.xrpChange.startsWith('-')) {
                decreases.push(xrpDisplay);
              } else {
                increases.push(xrpDisplay);
              }
            }
            
            // Add token changes
            for (const tc of balanceChanges.tokenChanges) {
              const tokenDisplay = `${tc.change.replace('-', '')} ${tc.currency}`;
              if (tc.change.startsWith('-')) {
                decreases.push(tokenDisplay);
              } else {
                increases.push(tokenDisplay);
              }
            }
            
            // Build display showing both sides
            if (decreases.length > 0 && increases.length > 0) {
              displayAmount = `-${decreases.join(', -')} → +${increases.join(', +')}`;
            } else if (increases.length > 0) {
              displayAmount = `+${increases.join(', +')}`;
            } else if (decreases.length > 0) {
              displayAmount = `-${decreases.join(', -')}`;
            }
            
            isOutgoing = decreases.length > 0;
          }
          
          // Fallback to transaction amount for regular payments
          if (!displayAmount) {
            let amountField = transaction.DeliverMax || transaction.Amount;
            
            // Check if this is a path payment (has delivered_amount in metadata)
            if (tx.meta && tx.meta.delivered_amount) {
              amountField = tx.meta.delivered_amount;
            }
            
            let amount = '0';
            let currency = 'XRP';
            
            if (typeof amountField === 'string') {
              // XRP payment (in drops)
              amount = xrplClient.formatXRPAmount(amountField);
              currency = 'XRP';
            } else if (typeof amountField === 'object' && amountField.value) {
              // Token payment
              amount = amountField.value;
              currency = xrplClient.decodeCurrency(amountField.currency);
            }
            
            displayAmount = `${isOutgoing ? '-' : '+'}${amount} ${currency}`;
          }
          
          transactions.push({
            id: transaction.hash || tx.hash,
            type: isDEXFill ? 'dex-fill' : (isOutgoing ? 'sent' : 'received'),
            amount: displayAmount,
            address: isOutgoing ? transaction.Destination : transaction.Account,
            time: new Date((transaction.date || 0) * 1000 + 946684800000),
            hash: transaction.hash || tx.hash,
            status: tx.meta?.TransactionResult === 'tesSUCCESS' ? 'confirmed' : 'failed',
            icon: isDEXFill ? ArrowLeftRight : (isOutgoing ? ArrowUp : ArrowDown),
            isDEXFill,
            iconBg: isDEXFill ? 'bg-purple-100 dark:bg-purple-900/30' : (isOutgoing ? 'bg-red-100 dark:bg-red-900/30' : 'bg-green-100 dark:bg-green-900/30'),
            iconColor: isDEXFill ? 'text-purple-600 dark:text-purple-400' : (isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'),
            amountColor: isDEXFill ? 'text-purple-600 dark:text-purple-400' : (isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'),
          });
        } else if (transaction?.TransactionType === 'OfferCreate' || transaction?.TransactionType === 'OfferCancel') {
          // Handle DEX offer transactions
          if (transaction.TransactionType === 'OfferCancel') {
            // OfferCancel only has OfferSequence, not TakerGets/TakerPays
            transactions.push({
              id: transaction.hash || tx.hash,
              type: 'exchange',
              transactionType: transaction.TransactionType,
              amount: `Offer #${transaction.OfferSequence || 'Unknown'}`,
              paidAmount: '',
              receivedAmount: '',
              address: 'DEX Trading',
              time: new Date((transaction.date || 0) * 1000 + 946684800000),
              hash: transaction.hash || tx.hash,
              status: tx.meta?.TransactionResult === 'tesSUCCESS' ? 'confirmed' : 'failed',
              icon: ArrowLeftRight,
              iconBg: 'bg-blue-100 dark:bg-blue-900/30',
              iconColor: 'text-blue-600 dark:text-blue-400',
              amountColor: 'text-blue-600 dark:text-blue-400',
            });
          } else {
            // OfferCreate has TakerGets/TakerPays
            const takerGets = transaction.TakerGets;
            const takerPays = transaction.TakerPays;
            const txHash = transaction.hash || tx.hash;
            
            if (takerGets && takerPays) {
              // Check if this OfferCreate is from another wallet
              const isFromOtherWallet = transaction.Account !== currentWallet?.address;
              
              // Determine what was received and what was paid
              let getsAmount = '0';
              let getsCurrency = 'XRP';
              let paysAmount = '0';
              let paysCurrency = 'XRP';
              
              // Determine which of our offers was filled (if from other wallet)
              let filledOfferSequences: number[] = [];
              if (isFromOtherWallet) {
                const offerFills = extractOfferFills(tx, currentWallet!.address);
                filledOfferSequences = offerFills.map(fill => fill.offerSequence);
              }
              
              if (isFromOtherWallet) {
                // For OfferCreate from another wallet, show only the balance changes to OUR wallet
                const balanceChanges = calculateBalanceChanges(tx, currentWallet!.address);
                
                if (balanceChanges.xrpChange || balanceChanges.tokenChanges.length > 0) {
                  // Extract what was paid (decreased) and received (increased)
                  
                  // Check XRP changes
                  if (balanceChanges.xrpChange) {
                    const xrpAmount = balanceChanges.xrpChange.replace('-', '');
                    if (balanceChanges.xrpChange.startsWith('-')) {
                      // XRP was paid
                      getsAmount = xrpAmount;
                      getsCurrency = 'XRP';
                    } else {
                      // XRP was received
                      paysAmount = xrpAmount;
                      paysCurrency = 'XRP';
                    }
                  }
                  
                  // Check token changes
                  balanceChanges.tokenChanges.forEach(tokenChange => {
                    const amount = tokenChange.change.replace('-', '');
                    const currency = xrplClient.decodeCurrency(tokenChange.currency);
                    
                    if (tokenChange.change.startsWith('-')) {
                      // Token was paid
                      getsAmount = amount;
                      getsCurrency = currency;
                    } else {
                      // Token was received
                      paysAmount = amount;
                      paysCurrency = currency;
                    }
                  });
                }
              } else {
                // For our own OfferCreate, show the full transaction amounts
                // Parse TakerGets (what taker gets = what YOU pay as offer creator)
                if (typeof takerGets === 'string') {
                  getsAmount = xrplClient.formatXRPAmount(takerGets);
                  getsCurrency = 'XRP';
                } else if (typeof takerGets === 'object' && takerGets.value) {
                  getsAmount = takerGets.value;
                  getsCurrency = xrplClient.decodeCurrency(takerGets.currency);
                }
                
                // Parse TakerPays (what taker pays = what YOU receive as offer creator)
                if (typeof takerPays === 'string') {
                  paysAmount = xrplClient.formatXRPAmount(takerPays);
                  paysCurrency = 'XRP';
                } else if (typeof takerPays === 'object' && takerPays.value) {
                  paysAmount = takerPays.value;
                  paysCurrency = xrplClient.decodeCurrency(takerPays.currency);
                }
              }
              
              // Check if we have this offer stored and enrich with fill status (only for our own offers)
              let storedOffer = null;
              if (!isFromOtherWallet) {
                // Try lookup by transaction hash first, then by sequence number
                storedOffer = offersByTxHash.get(txHash);
                
                if (!storedOffer && transaction.Sequence) {
                  storedOffer = offersBySequence.get(transaction.Sequence);
                }
              }
              
              // Round amounts to 4 decimal places
              const roundedGetsAmount = parseFloat(getsAmount).toFixed(4);
              const roundedPaysAmount = parseFloat(paysAmount).toFixed(4);
              
              let displayAmount = '';
              let displayAddress = 'DEX Trading';
              
              if (isFromOtherWallet && filledOfferSequences.length > 0) {
                // Show which of our offers was filled
                const offerSeqDisplay = filledOfferSequences.length === 1 
                  ? `Offer #${filledOfferSequences[0]}`
                  : `Offers #${filledOfferSequences.join(', #')}`;
                displayAddress = `Payment to Fill ${offerSeqDisplay}`;
                // For fills, highlight the received amount in green (stored in custom field)
                displayAmount = `Pay: ${roundedGetsAmount} ${getsCurrency} to <span class="text-green-600 dark:text-green-400">Receive: ${roundedPaysAmount} ${paysCurrency}</span>`;
              } else {
                displayAmount = `Pay: ${roundedGetsAmount} ${getsCurrency} to Receive: ${roundedPaysAmount} ${paysCurrency}`;
                
                if (!isFromOtherWallet) {
                  // Always show offer number for our own offers
                  displayAddress = `Offer #${transaction.Sequence}`;
                  
                  // Add fill status if there are fills
                  if (storedOffer && storedOffer.fills.length > 0) {
                    const enriched = enrichOfferWithStatus(storedOffer);
                    const fillStatus = enriched.isFullyExecuted 
                      ? 'Fully Filled'
                      : `${enriched.fillPercentage.toFixed(0)}% Filled`;
                    displayAmount = `${fillStatus} - ${displayAmount}`;
                  }
                }
              }
              
              transactions.push({
                id: txHash,
                type: 'exchange',
                transactionType: transaction.TransactionType, // Store OfferCreate or OfferCancel
                amount: displayAmount,
                paidAmount: `${getsAmount} ${getsCurrency}`,
                receivedAmount: `${paysAmount} ${paysCurrency}`,
                address: displayAddress,
                time: new Date((transaction.date || 0) * 1000 + 946684800000),
                hash: txHash,
                status: tx.meta?.TransactionResult === 'tesSUCCESS' ? 'confirmed' : 'failed',
                icon: ArrowLeftRight,
                iconBg: 'bg-blue-100 dark:bg-blue-900/30',
                iconColor: 'text-blue-600 dark:text-blue-400',
                amountColor: 'text-blue-600 dark:text-blue-400',
              });
            }
          }
        }
      });
    }

    // Add database transactions if no XRPL data
    if (transactions.length === 0 && dbTransactions) {
      dbTransactions.forEach((tx) => {
        const isOutgoing = tx.type === 'sent';
        transactions.push({
          id: tx.id.toString(),
          type: tx.type,
          amount: `${isOutgoing ? '-' : '+'}${tx.amount} ${tx.currency}`,
          address: tx.toAddress || tx.fromAddress || 'Unknown',
          time: new Date(tx.createdAt),
          hash: tx.txHash || null,
          status: tx.status,
          icon: isOutgoing ? ArrowUp : ArrowDown,
          iconBg: isOutgoing ? 'bg-red-100 dark:bg-red-900/30' : 'bg-green-100 dark:bg-green-900/30',
          iconColor: isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400',
          amountColor: isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400',
        });
      });
    }

    // Sort by time (newest first)
    return transactions.sort((a, b) => b.time.getTime() - a.time.getTime());
  };

  const transactions = formatTransactions();

  const formatAddress = (address: string) => {
    if (address.length > 10) {
      return `${address.slice(0, 6)}...${address.slice(-6)}`;
    }
    return address;
  };

  const formatDate = (date: Date) => {
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / (1000 * 60));
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

    if (diffMins < 60) {
      return `${diffMins}m ago`;
    } else if (diffHours < 24) {
      return `${diffHours}h ago`;
    } else if (diffDays < 7) {
      return `${diffDays}d ago`;
    } else {
      return date.toLocaleDateString();
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'confirmed':
        return 'text-green-600 dark:text-green-400';
      case 'pending':
        return 'text-yellow-600 dark:text-yellow-400';
      case 'failed':
        return 'text-red-600 dark:text-red-400';
      default:
        return 'text-muted-foreground';
    }
  };

  if (isLoading) {
    return (
      <div className="px-4 py-6">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold">Transaction History</h1>
          <Button variant="outline" size="sm" disabled>
            <Filter className="w-4 h-4" />
          </Button>
        </div>
        
        <div className="space-y-3">
          {[1, 2, 3, 4, 5].map((i) => (
            <div key={i} className="bg-white dark:bg-card border border-border rounded-xl p-4 animate-pulse">
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-muted rounded-full"></div>
                <div className="flex-1">
                  <div className="h-4 bg-muted rounded w-24 mb-2"></div>
                  <div className="h-3 bg-muted rounded w-32"></div>
                </div>
                <div>
                  <div className="h-4 bg-muted rounded w-16 mb-1"></div>
                  <div className="h-3 bg-muted rounded w-12"></div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="px-4 py-6">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Transaction History</h1>
        <Button variant="outline" size="sm">
          <Filter className="w-4 h-4" />
        </Button>
      </div>

      {transactions.length === 0 ? (
        <div className="bg-white dark:bg-card border border-border rounded-xl p-8 text-center">
          <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
            <ArrowLeftRight className="w-8 h-8 text-muted-foreground" />
          </div>
          <h3 className="font-semibold mb-2">No Transactions Yet</h3>
          <p className="text-muted-foreground text-sm">
            Your transaction history will appear here once you start using your wallet.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {transactions.map((transaction) => {
            const Icon = transaction.icon;
            return (
              <div
                key={transaction.id}
                className="bg-white dark:bg-card border border-border rounded-xl p-4"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center space-x-3">
                    <div className={`w-10 h-10 ${transaction.iconBg} rounded-full flex items-center justify-center`}>
                      <Icon className={`w-4 h-4 ${transaction.iconColor}`} />
                    </div>
                    <div>
                      <p className="font-medium">
                        {transaction.isDEXFill ? 'DEX Fill' : 
                         transaction.type === 'sent' ? 'Sent' : 
                         transaction.type === 'received' ? 'Received' : 
                         transaction.address?.startsWith('Payment to Fill') ? transaction.address :
                         transaction.address?.startsWith('Offer #') ? transaction.address :
                         transaction.transactionType === 'OfferCreate' ? 'Offer Created' : 
                         transaction.transactionType === 'OfferCancel' ? 'Offer Cancelled' : 'DEX Trade'}
                      </p>
                      {transaction.type !== 'exchange' && !transaction.isDEXFill && !transaction.address?.startsWith('Payment to Fill') && !transaction.address?.startsWith('Offer #') && (
                        <p className="text-sm text-muted-foreground">
                          {(transaction.type === 'sent' ? 'To:' : 'From:') + ' ' + formatAddress(transaction.address)}
                        </p>
                      )}
                      {transaction.isDEXFill && (
                        <p className="text-sm text-muted-foreground">
                          Offer executed automatically
                        </p>
                      )}
                    </div>
                  </div>
                  <div className="text-right">
                    <p 
                      className={`font-semibold ${transaction.amountColor}`}
                      dangerouslySetInnerHTML={{ __html: transaction.amount }}
                    />
                    <p className="text-xs text-muted-foreground">
                      {formatDate(transaction.time)}
                    </p>
                  </div>
                </div>
                
                <div className="flex items-center justify-between text-xs mt-3 pt-3 border-t border-border">
                  <span className={`px-2 py-1 rounded-full ${getStatusColor(transaction.status)} bg-muted`}>
                    {transaction.status}
                  </span>
                  {transaction.hash && (
                    <a 
                      href={getXRPScanUrl(transaction.hash)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary hover:text-primary/80 font-mono text-xs break-all transition-colors"
                      data-testid={`link-xrpscan-${transaction.hash}`}
                    >
                      {transaction.hash}
                    </a>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
