import { ArrowUp, ArrowDown, ArrowLeftRight, Link, Settings, Image, Droplets, FileText, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useWallet } from '@/hooks/use-wallet';
import { useTransactions } from '@/hooks/use-wallet';
import { useAccountTransactions } from '@/hooks/use-xrpl';
import { xrplClient } from '@/lib/xrpl-client';
import { calculateBalanceChanges, extractOfferFills, enrichOfferWithStatus } from '@/lib/dex-utils';
import { browserStorage } from '@/lib/browser-storage';
import { AddressFormat, truncateAddress } from '@/lib/format-address';

interface RecentTransactionsProps {
  onViewAllClick: () => void;
}

export function RecentTransactions({ onViewAllClick }: RecentTransactionsProps) {
  const { currentWallet } = useWallet();
  const network = currentWallet?.network ?? 'mainnet';
  const { data: dbTransactions } = useTransactions(currentWallet?.id || null);
  const { data: xrplTransactions } = useAccountTransactions(currentWallet?.address || null, network, 10);

  // Combine and format transactions from both sources
  const formatTransactions = () => {
    const transactions: any[] = [];
    
    // Preload stored offers for quick lookup
    const storedOffers = currentWallet 
      ? browserStorage.getOffersByWallet(currentWallet.address, network)
      : [];
    
    // Create maps for lookup by both transaction hash AND sequence number
    const offersByTxHash = new Map(
      storedOffers
        .filter((offer: any) => offer.createdTxHash)
        .map((offer: any) => [offer.createdTxHash, offer])
    );
    
    const offersBySequence = new Map(
      storedOffers.map((offer: any) => [offer.sequence, offer])
    );

    // Add XRPL transactions
    if (xrplTransactions?.transactions) {
      xrplTransactions.transactions.slice(0, 5).forEach((tx: any) => {
        // Handle both tx.tx_json (historical) and tx structure (real-time)
        const transaction = tx.tx_json || tx.tx || tx;
        
        if (transaction?.TransactionType === 'Payment') {
          // Check if this payment was generated by an offer fill
          const offerFills = currentWallet ? extractOfferFills(tx, currentWallet.address) : [];
          const isDEXFill = offerFills.length > 0;
          
          // Calculate actual balance changes from metadata
          const balanceChanges = currentWallet ? calculateBalanceChanges(tx, currentWallet.address) : { xrpChange: null, tokenChanges: [] };
          
          // Skip transactions where current wallet is neither sender nor receiver
          // UNLESS there are balance changes (which means we're involved indirectly via DEX)
          const isSender = transaction.Account === currentWallet?.address;
          const isReceiver = transaction.Destination === currentWallet?.address;
          const hasBalanceChanges = balanceChanges.xrpChange || balanceChanges.tokenChanges.length > 0;
          
          if (!isSender && !isReceiver && !hasBalanceChanges) {
            return; // Skip this transaction
          }
          
          let displayAmount = '';
          let isOutgoing = isSender;
          
          // For DEX fills, show both sides of the trade
          if (isDEXFill || hasBalanceChanges) {
            const increases: string[] = [];
            const decreases: string[] = [];
            
            // Add XRP changes
            if (balanceChanges.xrpChange) {
              const xrpDisplay = `${balanceChanges.xrpChange.replace('-', '')} XRP`;
              if (balanceChanges.xrpChange.startsWith('-')) {
                decreases.push(xrpDisplay);
              } else {
                increases.push(xrpDisplay);
              }
            }
            
            // Add token changes
            for (const tc of balanceChanges.tokenChanges) {
              const tokenDisplay = `${tc.change.replace('-', '')} ${tc.currency}`;
              if (tc.change.startsWith('-')) {
                decreases.push(tokenDisplay);
              } else {
                increases.push(tokenDisplay);
              }
            }
            
            // Build display showing both sides
            if (decreases.length > 0 && increases.length > 0) {
              displayAmount = `-${decreases.join(', -')} → +${increases.join(', +')}`;
            } else if (increases.length > 0) {
              displayAmount = `+${increases.join(', +')}`;
            } else if (decreases.length > 0) {
              displayAmount = `-${decreases.join(', -')}`;
            }
            
            isOutgoing = decreases.length > 0;
          }
          
          // Fallback to transaction amount for regular payments
          if (!displayAmount) {
            let amountField = transaction.DeliverMax || transaction.Amount;
            
            // Check if this is a path payment (has delivered_amount in metadata)
            if (tx.meta && tx.meta.delivered_amount) {
              amountField = tx.meta.delivered_amount;
            }
            
            let amount = '0';
            let currency = 'XRP';
            
            if (typeof amountField === 'string') {
              // XRP payment (in drops)
              amount = xrplClient.formatXRPAmount(amountField);
              currency = 'XRP';
            } else if (typeof amountField === 'object' && amountField.value) {
              // Token payment
              amount = amountField.value;
              currency = xrplClient.decodeCurrency(amountField.currency);
            }
            
            displayAmount = `${isOutgoing ? '-' : '+'}${amount} ${currency}`;
          }
          
          transactions.push({
            id: transaction.hash || tx.hash,
            type: isDEXFill ? 'dex-fill' : (isOutgoing ? 'sent' : 'received'),
            amount: displayAmount,
            address: isOutgoing ? transaction.Destination : transaction.Account,
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: isDEXFill ? ArrowLeftRight : (isOutgoing ? ArrowUp : ArrowDown),
            isDEXFill,
            iconBg: isDEXFill ? 'bg-purple-100 dark:bg-purple-900/30' : (isOutgoing ? 'bg-red-100 dark:bg-red-900/30' : 'bg-green-100 dark:bg-green-900/30'),
            iconColor: isDEXFill ? 'text-purple-600 dark:text-purple-400' : (isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'),
            amountColor: isDEXFill ? 'text-purple-600 dark:text-purple-400' : (isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'),
          });
        } else if (transaction?.TransactionType === 'TrustSet') {
          // TrustSet - Adding or modifying trust lines
          const limitAmount = transaction.LimitAmount;
          let currency = 'Unknown';
          let limit = '0';
          
          if (typeof limitAmount === 'object' && limitAmount.currency) {
            currency = xrplClient.decodeCurrency(limitAmount.currency);
            limit = limitAmount.value || '0';
          }
          
          const isRemovingTrust = limit === '0';
          
          transactions.push({
            id: transaction.hash || tx.hash,
            type: 'trustline',
            amount: isRemovingTrust ? `Removed ${currency}` : `${currency} trustline set`,
            address: isRemovingTrust ? 'Trust line removed' : `Limit: ${limit}`,
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: isRemovingTrust ? X : Link,
            iconBg: isRemovingTrust ? 'bg-red-100 dark:bg-red-900/30' : 'bg-cyan-100 dark:bg-cyan-900/30',
            iconColor: isRemovingTrust ? 'text-red-600 dark:text-red-400' : 'text-cyan-600 dark:text-cyan-400',
            amountColor: isRemovingTrust ? 'text-red-600 dark:text-red-400' : 'text-cyan-600 dark:text-cyan-400',
          });
        } else if (transaction?.TransactionType === 'AccountSet') {
          // AccountSet - Account settings changes
          transactions.push({
            id: transaction.hash || tx.hash,
            type: 'account-set',
            amount: 'Account settings updated',
            address: 'Configuration',
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: Settings,
            iconBg: 'bg-gray-100 dark:bg-gray-800',
            iconColor: 'text-gray-600 dark:text-gray-400',
            amountColor: 'text-gray-600 dark:text-gray-400',
          });
        } else if (transaction?.TransactionType?.startsWith('NFToken')) {
          // NFT transactions
          let nftType = transaction.TransactionType.replace('NFToken', '');
          let description = `NFT ${nftType}`;
          let bgColor = 'bg-fuchsia-100 dark:bg-fuchsia-900/30';
          let textColor = 'text-fuchsia-600 dark:text-fuchsia-400';
          
          if (nftType === 'Burn') {
            bgColor = 'bg-red-100 dark:bg-red-900/30';
            textColor = 'text-red-600 dark:text-red-400';
          } else if (nftType === 'AcceptOffer') {
            bgColor = 'bg-green-100 dark:bg-green-900/30';
            textColor = 'text-green-600 dark:text-green-400';
          }
          
          transactions.push({
            id: transaction.hash || tx.hash,
            type: 'nft',
            amount: description,
            address: 'NFT',
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: Image,
            iconBg: bgColor,
            iconColor: textColor,
            amountColor: textColor,
          });
        } else if (transaction?.TransactionType?.startsWith('AMM')) {
          // AMM transactions
          let ammType = transaction.TransactionType.replace('AMM', '');
          let bgColor = 'bg-sky-100 dark:bg-sky-900/30';
          let textColor = 'text-sky-600 dark:text-sky-400';
          
          if (ammType === 'Delete' || ammType === 'Withdraw') {
            bgColor = 'bg-orange-100 dark:bg-orange-900/30';
            textColor = 'text-orange-600 dark:text-orange-400';
          }
          
          transactions.push({
            id: transaction.hash || tx.hash,
            type: 'amm',
            amount: `AMM ${ammType}`,
            address: 'Liquidity Pool',
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: Droplets,
            iconBg: bgColor,
            iconColor: textColor,
            amountColor: textColor,
          });
        } else if (transaction?.TransactionType && 
                   !['Payment', 'OfferCreate', 'OfferCancel', 'TrustSet', 'AccountSet'].includes(transaction.TransactionType) &&
                   !transaction.TransactionType.startsWith('NFToken') &&
                   !transaction.TransactionType.startsWith('AMM')) {
          // Catch-all for other transaction types
          transactions.push({
            id: transaction.hash || tx.hash,
            type: 'other',
            amount: transaction.TransactionType,
            address: 'Transaction',
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: FileText,
            iconBg: 'bg-gray-100 dark:bg-gray-800',
            iconColor: 'text-gray-600 dark:text-gray-400',
            amountColor: 'text-gray-600 dark:text-gray-400',
          });
        } else if (transaction?.TransactionType === 'OfferCreate' || transaction?.TransactionType === 'OfferCancel') {
          // Handle DEX offer transactions
          if (transaction.TransactionType === 'OfferCancel') {
            // OfferCancel only has OfferSequence, not TakerGets/TakerPays
            transactions.push({
              id: transaction.hash || tx.hash,
              type: 'exchange',
              transactionType: transaction.TransactionType,
              amount: `Offer #${transaction.OfferSequence || 'Unknown'}`,
              paidAmount: '',
              receivedAmount: '',
              address: 'DEX Trading',
              time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
              icon: ArrowLeftRight,
              iconBg: 'bg-blue-100 dark:bg-blue-900/30',
              iconColor: 'text-blue-600 dark:text-blue-400',
              amountColor: 'text-blue-600 dark:text-blue-400',
            });
          } else {
            // OfferCreate has TakerGets/TakerPays
            const takerGets = transaction.TakerGets;
            const takerPays = transaction.TakerPays;
            const txHash = transaction.hash || tx.hash;
            
            if (takerGets && takerPays) {
              // Check if this OfferCreate is from another wallet
              const isFromOtherWallet = transaction.Account !== currentWallet?.address;
              
              // Determine which of our offers was filled (if from other wallet)
              let filledOfferSequences: number[] = [];
              if (isFromOtherWallet) {
                const offerFills = extractOfferFills(tx, currentWallet!.address);
                filledOfferSequences = offerFills.map(fill => fill.offerSequence);
              }
              
              // Determine what was received and what was paid
              let getsAmount = '0';
              let getsCurrency = 'XRP';
              let paysAmount = '0';
              let paysCurrency = 'XRP';
              
              // For all OfferCreate transactions, use actual balance changes to show what really happened
              const balanceChanges = calculateBalanceChanges(tx, currentWallet!.address);
              
              // Track if we found actual balance changes (indicating the offer was filled)
              let hasBalanceChanges = balanceChanges.xrpChange || balanceChanges.tokenChanges.length > 0;
              
              if (hasBalanceChanges) {
                // Extract what was paid (decreased) and received (increased) from actual balance changes
                
                // Check XRP changes
                if (balanceChanges.xrpChange) {
                  const xrpAmount = balanceChanges.xrpChange.replace('-', '');
                  if (balanceChanges.xrpChange.startsWith('-')) {
                    // XRP was paid (we spent XRP)
                    getsAmount = xrpAmount;
                    getsCurrency = 'XRP';
                  } else {
                    // XRP was received (we got XRP)
                    paysAmount = xrpAmount;
                    paysCurrency = 'XRP';
                  }
                }
                
                // Check token changes
                balanceChanges.tokenChanges.forEach(tokenChange => {
                  const amount = tokenChange.change.replace('-', '');
                  const currency = xrplClient.decodeCurrency(tokenChange.currency);
                  
                  if (tokenChange.change.startsWith('-')) {
                    // Token was paid (we spent token)
                    getsAmount = amount;
                    getsCurrency = currency;
                  } else {
                    // Token was received (we got token)
                    paysAmount = amount;
                    paysCurrency = currency;
                  }
                });
              } else if (!isFromOtherWallet) {
                // No balance changes detected - show the submitted offer amounts (unfilled offer)
                // Parse TakerGets (what taker gets = what YOU pay as offer creator)
                if (typeof takerGets === 'string') {
                  getsAmount = xrplClient.formatXRPAmount(takerGets);
                  getsCurrency = 'XRP';
                } else if (typeof takerGets === 'object' && takerGets.value) {
                  getsAmount = takerGets.value;
                  getsCurrency = xrplClient.decodeCurrency(takerGets.currency);
                }
                
                // Parse TakerPays (what taker pays = what YOU receive as offer creator)
                if (typeof takerPays === 'string') {
                  paysAmount = xrplClient.formatXRPAmount(takerPays);
                  paysCurrency = 'XRP';
                } else if (typeof takerPays === 'object' && takerPays.value) {
                  paysAmount = takerPays.value;
                  paysCurrency = xrplClient.decodeCurrency(takerPays.currency);
                }
              }
              
              // Check if this offer has fill status (only for our own offers)
              let storedOffer = null;
              if (!isFromOtherWallet) {
                storedOffer = offersByTxHash.get(txHash);
                if (!storedOffer && transaction.Sequence) {
                  storedOffer = offersBySequence.get(transaction.Sequence);
                }
              }
              
              // Round amounts to 4 decimal places
              const roundedGetsAmount = parseFloat(getsAmount).toFixed(4);
              const roundedPaysAmount = parseFloat(paysAmount).toFixed(4);
              
              let displayAmount = '';
              let displayAddress = 'DEX Trading';
              let transactionTypeOverride: string | undefined;
              
              if (isFromOtherWallet && filledOfferSequences.length > 0) {
                // Show which of our offers was filled by another wallet's OfferCreate
                const offerSeqDisplay = filledOfferSequences.length === 1 
                  ? `Offer #${filledOfferSequences[0]}`
                  : `Offers #${filledOfferSequences.join(', #')}`;
                displayAddress = `Partial Fill - ${offerSeqDisplay}`;
                // For fills, highlight the received amount in green
                displayAmount = `Paid: ${roundedGetsAmount} ${getsCurrency} - <span class="text-green-600 dark:text-green-400">Received: ${roundedPaysAmount} ${paysCurrency}</span>`;
              } else if (!isFromOtherWallet && hasBalanceChanges) {
                // Our own OfferCreate that was immediately filled (taker trade)
                // Show the actual amounts traded with "Traded" label
                displayAddress = `DEX Trade`;
                transactionTypeOverride = 'DEX Trade';
                displayAmount = `Paid: ${roundedGetsAmount} ${getsCurrency} - <span class="text-green-600 dark:text-green-400">Received: ${roundedPaysAmount} ${paysCurrency}</span>`;
              } else if (!isFromOtherWallet) {
                // Our own OfferCreate that created an offer on the book (unfilled or partial)
                displayAddress = `Offer #${transaction.Sequence}`;
                displayAmount = `Pay: ${roundedGetsAmount} ${getsCurrency} to Receive: ${roundedPaysAmount} ${paysCurrency}`;
                
                // Add fill status if there are fills from stored offer data
                if (storedOffer && (storedOffer as any).fills && (storedOffer as any).fills.length > 0) {
                  const enriched = enrichOfferWithStatus(storedOffer as any);
                  const fillStatus = enriched.isFullyExecuted 
                    ? 'Fully Filled'
                    : `${enriched.fillPercentage.toFixed(0)}% Filled`;
                  displayAmount = `${fillStatus} - ${displayAmount}`;
                }
              } else {
                // Other wallet's OfferCreate that didn't fill our offers
                displayAmount = `Pay: ${roundedGetsAmount} ${getsCurrency} to Receive: ${roundedPaysAmount} ${paysCurrency}`;
              }
              
              // Use green styling for filled trades to indicate XRP/tokens received
              const isFilled = hasBalanceChanges && !isFromOtherWallet;
              
              transactions.push({
                id: txHash,
                type: isFilled ? 'dex-fill' : 'exchange',
                transactionType: transactionTypeOverride || transaction.TransactionType,
                amount: displayAmount,
                paidAmount: `${getsAmount} ${getsCurrency}`,
                receivedAmount: `${paysAmount} ${paysCurrency}`,
                address: displayAddress,
                time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
                icon: ArrowLeftRight,
                iconBg: isFilled ? 'bg-green-100 dark:bg-green-900/30' : 'bg-blue-100 dark:bg-blue-900/30',
                iconColor: isFilled ? 'text-green-600 dark:text-green-400' : 'text-blue-600 dark:text-blue-400',
                amountColor: isFilled ? 'text-green-600 dark:text-green-400' : 'text-blue-600 dark:text-blue-400',
              });
            }
          }
        }
      });
    }

    // Add database transactions if no XRPL data
    if (transactions.length === 0 && dbTransactions) {
      dbTransactions.slice(0, 5).forEach((tx) => {
        const isOutgoing = tx.type === 'sent';
        transactions.push({
          id: tx.id.toString(),
          type: tx.type,
          amount: `${isOutgoing ? '-' : '+'}${tx.amount} ${tx.currency}`,
          address: tx.toAddress || tx.fromAddress || 'Unknown',
          time: new Date(tx.createdAt).toLocaleDateString() || 'Recently',
          icon: isOutgoing ? ArrowUp : ArrowDown,
          iconBg: isOutgoing ? 'bg-red-100 dark:bg-red-900/30' : 'bg-green-100 dark:bg-green-900/30',
          iconColor: isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400',
          amountColor: isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400',
        });
      });
    }

    return transactions;
  };

  const transactions = formatTransactions();


  return (
    <section className="px-4 py-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold">Recent Activity</h3>
        <Button
          onClick={onViewAllClick}
          variant="ghost"
          className="text-primary font-medium text-sm p-0 h-auto"
        >
          View All
        </Button>
      </div>
      
      {transactions.length === 0 ? (
        <div className="bg-white dark:bg-card border border-border rounded-xl p-6 text-center">
          <p className="text-muted-foreground">No transactions yet</p>
          <p className="text-sm text-muted-foreground mt-1">
            Your transaction history will appear here
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {transactions.map((transaction) => {
            const Icon = transaction.icon;
            return (
              <div
                key={transaction.id}
                className="bg-white dark:bg-card border border-border rounded-xl p-4"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className={`w-10 h-10 ${transaction.iconBg} rounded-full flex items-center justify-center`}>
                      <Icon className={`w-4 h-4 ${transaction.iconColor}`} />
                    </div>
                    <div>
                      <p className="font-medium">
                        {transaction.type === 'dex-fill' && transaction.transactionType === 'DEX Trade' ? 'DEX Trade' :
                         transaction.type === 'dex-fill' ? 'DEX Fill' : 
                         transaction.type === 'sent' ? 'Sent' : 
                         transaction.type === 'received' ? 'Received' : 
                         transaction.type === 'trustline' ? 'Trust Line' :
                         transaction.type === 'account-set' ? 'Account Settings' :
                         transaction.type === 'nft' ? transaction.amount :
                         transaction.type === 'amm' ? transaction.amount :
                         transaction.type === 'other' ? transaction.amount :
                         transaction.address?.startsWith('Payment to Fill') ? transaction.address :
                         transaction.address?.startsWith('Offer #') ? transaction.address :
                         transaction.transactionType === 'OfferCreate' ? 'Offer Created' : 
                         transaction.transactionType === 'OfferCancel' ? 'Offer Cancelled' : 'DEX Trade'}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        {transaction.type === 'sent' && `To: ${AddressFormat.short(transaction.address)}`}
                        {transaction.type === 'received' && `From: ${AddressFormat.short(transaction.address)}`}
                        {transaction.type === 'dex-fill' && transaction.transactionType === 'DEX Trade' && 'Instant trade'}
                        {transaction.type === 'dex-fill' && transaction.transactionType !== 'DEX Trade' && 'Offer filled'}
                        {transaction.type === 'exchange' && !transaction.address?.startsWith('Partial Fill -') && !transaction.address?.startsWith('Offer #') && transaction.address}
                        {(transaction.address?.startsWith('Partial Fill -') || transaction.address?.startsWith('Offer #')) && ''}
                        {transaction.type === 'trustline' && transaction.address}
                        {transaction.type === 'account-set' && transaction.address}
                        {transaction.type === 'nft' && transaction.address}
                        {transaction.type === 'amm' && transaction.address}
                        {transaction.type === 'other' && transaction.address}
                      </p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p 
                      className={`font-semibold ${transaction.amountColor}`}
                      dangerouslySetInnerHTML={{ __html: transaction.amount }}
                    />
                    <p className="text-xs text-muted-foreground">{transaction.time}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
