import { ArrowUp, ArrowDown, ArrowLeftRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useWallet } from '@/hooks/use-wallet';
import { useTransactions } from '@/hooks/use-wallet';
import { useAccountTransactions } from '@/hooks/use-xrpl';
import { xrplClient } from '@/lib/xrpl-client';
import { calculateBalanceChanges, extractOfferFills } from '@/lib/dex-utils';
import { browserStorage } from '@/lib/browser-storage';

interface RecentTransactionsProps {
  onViewAllClick: () => void;
}

export function RecentTransactions({ onViewAllClick }: RecentTransactionsProps) {
  const { currentWallet } = useWallet();
  const network = currentWallet?.network ?? 'mainnet';
  const { data: dbTransactions } = useTransactions(currentWallet?.id || null);
  const { data: xrplTransactions } = useAccountTransactions(currentWallet?.address || null, network, 10);

  // Combine and format transactions from both sources
  const formatTransactions = () => {
    const transactions: any[] = [];
    
    // Preload stored offers for quick lookup
    const storedOffers = currentWallet 
      ? browserStorage.getOffersByWallet(currentWallet.address, network)
      : [];
    
    // Create maps for lookup by both transaction hash AND sequence number
    const offersByTxHash = new Map(
      storedOffers
        .filter((offer: any) => offer.createdTxHash)
        .map((offer: any) => [offer.createdTxHash, offer])
    );
    
    const offersBySequence = new Map(
      storedOffers.map((offer: any) => [offer.sequence, offer])
    );

    // Add XRPL transactions
    if (xrplTransactions?.transactions) {
      xrplTransactions.transactions.slice(0, 5).forEach((tx: any) => {
        // Handle both tx.tx_json (historical) and tx structure (real-time)
        const transaction = tx.tx_json || tx.tx || tx;
        
        if (transaction?.TransactionType === 'Payment') {
          // Check if this payment was generated by an offer fill
          const offerFills = currentWallet ? extractOfferFills(tx, currentWallet.address) : [];
          const isDEXFill = offerFills.length > 0;
          
          // Calculate actual balance changes from metadata
          const balanceChanges = currentWallet ? calculateBalanceChanges(tx, currentWallet.address) : { xrpChange: null, tokenChanges: [] };
          
          // Skip transactions where current wallet is neither sender nor receiver
          // UNLESS there are balance changes (which means we're involved indirectly via DEX)
          const isSender = transaction.Account === currentWallet?.address;
          const isReceiver = transaction.Destination === currentWallet?.address;
          const hasBalanceChanges = balanceChanges.xrpChange || balanceChanges.tokenChanges.length > 0;
          
          if (!isSender && !isReceiver && !hasBalanceChanges) {
            return; // Skip this transaction
          }
          
          let displayAmount = '';
          let isOutgoing = isSender;
          
          // For DEX fills, show both sides of the trade
          if (isDEXFill || hasBalanceChanges) {
            const increases: string[] = [];
            const decreases: string[] = [];
            
            // Add XRP changes
            if (balanceChanges.xrpChange) {
              const xrpDisplay = `${balanceChanges.xrpChange.replace('-', '')} XRP`;
              if (balanceChanges.xrpChange.startsWith('-')) {
                decreases.push(xrpDisplay);
              } else {
                increases.push(xrpDisplay);
              }
            }
            
            // Add token changes
            for (const tc of balanceChanges.tokenChanges) {
              const tokenDisplay = `${tc.change.replace('-', '')} ${tc.currency}`;
              if (tc.change.startsWith('-')) {
                decreases.push(tokenDisplay);
              } else {
                increases.push(tokenDisplay);
              }
            }
            
            // Build display showing both sides
            if (decreases.length > 0 && increases.length > 0) {
              displayAmount = `-${decreases.join(', -')} → +${increases.join(', +')}`;
            } else if (increases.length > 0) {
              displayAmount = `+${increases.join(', +')}`;
            } else if (decreases.length > 0) {
              displayAmount = `-${decreases.join(', -')}`;
            }
            
            isOutgoing = decreases.length > 0;
          }
          
          // Fallback to transaction amount for regular payments
          if (!displayAmount) {
            let amountField = transaction.DeliverMax || transaction.Amount;
            
            // Check if this is a path payment (has delivered_amount in metadata)
            if (tx.meta && tx.meta.delivered_amount) {
              amountField = tx.meta.delivered_amount;
            }
            
            let amount = '0';
            let currency = 'XRP';
            
            if (typeof amountField === 'string') {
              // XRP payment (in drops)
              amount = xrplClient.formatXRPAmount(amountField);
              currency = 'XRP';
            } else if (typeof amountField === 'object' && amountField.value) {
              // Token payment
              amount = amountField.value;
              currency = xrplClient.decodeCurrency(amountField.currency);
            }
            
            displayAmount = `${isOutgoing ? '-' : '+'}${amount} ${currency}`;
          }
          
          transactions.push({
            id: transaction.hash || tx.hash,
            type: isDEXFill ? 'dex-fill' : (isOutgoing ? 'sent' : 'received'),
            amount: displayAmount,
            address: isOutgoing ? transaction.Destination : transaction.Account,
            time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
            icon: isDEXFill ? ArrowLeftRight : (isOutgoing ? ArrowUp : ArrowDown),
            isDEXFill,
            iconBg: isDEXFill ? 'bg-purple-100 dark:bg-purple-900/30' : (isOutgoing ? 'bg-red-100 dark:bg-red-900/30' : 'bg-green-100 dark:bg-green-900/30'),
            iconColor: isDEXFill ? 'text-purple-600 dark:text-purple-400' : (isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'),
            amountColor: isDEXFill ? 'text-purple-600 dark:text-purple-400' : (isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'),
          });
        } else if (transaction?.TransactionType === 'OfferCreate' || transaction?.TransactionType === 'OfferCancel') {
          // Handle DEX offer transactions
          if (transaction.TransactionType === 'OfferCancel') {
            // OfferCancel only has OfferSequence, not TakerGets/TakerPays
            transactions.push({
              id: transaction.hash || tx.hash,
              type: 'exchange',
              transactionType: transaction.TransactionType,
              amount: `Offer #${transaction.OfferSequence || 'Unknown'}`,
              paidAmount: '',
              receivedAmount: '',
              address: 'DEX Trading',
              time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
              icon: ArrowLeftRight,
              iconBg: 'bg-blue-100 dark:bg-blue-900/30',
              iconColor: 'text-blue-600 dark:text-blue-400',
              amountColor: 'text-blue-600 dark:text-blue-400',
            });
          } else {
            // OfferCreate has TakerGets/TakerPays
            const takerGets = transaction.TakerGets;
            const takerPays = transaction.TakerPays;
            
            if (takerGets && takerPays) {
              // Determine what was received and what was paid
              let getsAmount = '0';
              let getsCurrency = 'XRP';
              let paysAmount = '0';
              let paysCurrency = 'XRP';
              
              // Parse TakerGets (what taker gets = what YOU pay as offer creator)
              if (typeof takerGets === 'string') {
                getsAmount = xrplClient.formatXRPAmount(takerGets);
                getsCurrency = 'XRP';
              } else if (typeof takerGets === 'object' && takerGets.value) {
                getsAmount = takerGets.value;
                getsCurrency = xrplClient.decodeCurrency(takerGets.currency);
              }
              
              // Parse TakerPays (what taker pays = what YOU receive as offer creator)
              if (typeof takerPays === 'string') {
                paysAmount = xrplClient.formatXRPAmount(takerPays);
                paysCurrency = 'XRP';
              } else if (typeof takerPays === 'object' && takerPays.value) {
                paysAmount = takerPays.value;
                paysCurrency = xrplClient.decodeCurrency(takerPays.currency);
              }
              
              // Check if this offer has fill status
              const txHash = transaction.hash || tx.hash;
              let storedOffer = offersByTxHash.get(txHash);
              if (!storedOffer && transaction.Sequence) {
                storedOffer = offersBySequence.get(transaction.Sequence);
              }
              
              let fillStatusText = '';
              
              if (storedOffer && (storedOffer as any).fills && (storedOffer as any).fills.length > 0) {
                // Calculate fill percentage based on original amounts
                const totalFilled = (storedOffer as any).fills.reduce((sum: number, fill: any) => sum + parseFloat(fill.amountFilled), 0);
                const originalAmount = parseFloat((storedOffer as any).originalTakerPays);
                const fillPercentage = Math.min(100, (totalFilled / originalAmount) * 100);
                
                if (fillPercentage >= 99.9) {
                  fillStatusText = 'Fully Filled - ';
                } else {
                  fillStatusText = `${fillPercentage.toFixed(0)}% Filled - `;
                }
              }
              
              transactions.push({
                id: txHash,
                type: 'exchange',
                transactionType: transaction.TransactionType,
                amount: `${fillStatusText}Pay: ${getsAmount} ${getsCurrency} to Receive: ${paysAmount} ${paysCurrency}`,
                paidAmount: `${getsAmount} ${getsCurrency}`,
                receivedAmount: `${paysAmount} ${paysCurrency}`,
                address: 'DEX Trading',
                time: new Date((transaction.date || 0) * 1000 + 946684800000).toLocaleDateString() || 'Recently',
                icon: ArrowLeftRight,
                iconBg: 'bg-blue-100 dark:bg-blue-900/30',
                iconColor: 'text-blue-600 dark:text-blue-400',
                amountColor: 'text-blue-600 dark:text-blue-400',
              });
            }
          }
        }
      });
    }

    // Add database transactions if no XRPL data
    if (transactions.length === 0 && dbTransactions) {
      dbTransactions.slice(0, 5).forEach((tx) => {
        const isOutgoing = tx.type === 'sent';
        transactions.push({
          id: tx.id.toString(),
          type: tx.type,
          amount: `${isOutgoing ? '-' : '+'}${tx.amount} ${tx.currency}`,
          address: tx.toAddress || tx.fromAddress || 'Unknown',
          time: new Date(tx.createdAt).toLocaleDateString() || 'Recently',
          icon: isOutgoing ? ArrowUp : ArrowDown,
          iconBg: isOutgoing ? 'bg-red-100 dark:bg-red-900/30' : 'bg-green-100 dark:bg-green-900/30',
          iconColor: isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400',
          amountColor: isOutgoing ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400',
        });
      });
    }

    return transactions;
  };

  const transactions = formatTransactions();

  const formatAddress = (address: string) => {
    if (address.length > 10) {
      return `${address.slice(0, 4)}...${address.slice(-4)}`;
    }
    return address;
  };

  return (
    <section className="px-4 py-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold">Recent Activity</h3>
        <Button
          onClick={onViewAllClick}
          variant="ghost"
          className="text-primary font-medium text-sm p-0 h-auto"
        >
          View All
        </Button>
      </div>
      
      {transactions.length === 0 ? (
        <div className="bg-white dark:bg-card border border-border rounded-xl p-6 text-center">
          <p className="text-muted-foreground">No transactions yet</p>
          <p className="text-sm text-muted-foreground mt-1">
            Your transaction history will appear here
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {transactions.map((transaction) => {
            const Icon = transaction.icon;
            return (
              <div
                key={transaction.id}
                className="bg-white dark:bg-card border border-border rounded-xl p-4"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className={`w-10 h-10 ${transaction.iconBg} rounded-full flex items-center justify-center`}>
                      <Icon className={`w-4 h-4 ${transaction.iconColor}`} />
                    </div>
                    <div>
                      <p className="font-medium">
                        {transaction.type === 'dex-fill' ? 'DEX Fill' : transaction.type === 'sent' ? 'Sent' : transaction.type === 'received' ? 'Received' : transaction.transactionType === 'OfferCreate' ? 'Offer Created' : transaction.transactionType === 'OfferCancel' ? 'Offer Cancelled' : 'DEX Trade'}
                      </p>
                      {transaction.type !== 'exchange' && transaction.type !== 'dex-fill' && (
                        <p className="text-sm text-muted-foreground">
                          {(transaction.type === 'sent' ? 'To:' : 'From:') + ' ' + formatAddress(transaction.address)}
                        </p>
                      )}
                    </div>
                  </div>
                  <div className="text-right">
                    <p className={`font-semibold ${transaction.amountColor}`}>
                      {transaction.amount}
                    </p>
                    <p className="text-xs text-muted-foreground">{transaction.time}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
